name: Pylint + flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install flake8
    - name: Analysing the code with pylint
      if: always()
      run: |
        pylint $(git ls-files '*.py') --disable=C --disable=R --disable=W --disable=E
    - name: Analysing the code with flake8
      if: always()
      run: |
        flake8 --extend-ignore E501
    - name: Run unittests
      if: always()
      run: |
        pytest tests
